//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServerService")]
    public interface IServerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/Test", ReplyAction="http://tempuri.org/IServerService/TestResponse")]
        bool Test(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/StoreSession", ReplyAction="http://tempuri.org/IServerService/StoreSessionResponse")]
        void StoreSession(string sessionName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/GetSessionName", ReplyAction="http://tempuri.org/IServerService/GetSessionNameResponse")]
        string GetSessionName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/SendByteData", ReplyAction="http://tempuri.org/IServerService/SendByteDataResponse")]
        void SendByteData(byte[] data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServerServiceChannel : Client.ServiceReference1.IServerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServerServiceClient : System.ServiceModel.ClientBase<Client.ServiceReference1.IServerService>, Client.ServiceReference1.IServerService {
        
        public ServerServiceClient() {
        }
        
        public ServerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Test(string input) {
            return base.Channel.Test(input);
        }
        
        public void StoreSession(string sessionName) {
            base.Channel.StoreSession(sessionName);
        }
        
        public string GetSessionName() {
            return base.Channel.GetSessionName();
        }
        
        public void SendByteData(byte[] data) {
            base.Channel.SendByteData(data);
        }
    }
}
